[package]
name = "kinfer-kbot"
version = "0.1.0"
edition = "2021"

[dependencies]

kinfer = "0.4.1"

[target.'cfg(target_os = "linux")'.dependencies]

robstride = { version = "0.3.4", features = ["instant_command"] }
imu = "0.7.3"
